# Generated by Django 3.2.8 on 2021-10-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAndAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField()),
            ],
            options={
                'verbose_name': 'Question and answer',
                'verbose_name_plural': 'Questions and answers',
            },
        ),
    ]
